// Generated by the offline prepare action. No source paths or credentials.
export const pilotSources = {
  "fuji": {
    "mime": "image/jpeg",
    "width": 3024,
    "height": 4032,
    "bytes": 1587326,
    "sha256": "28cca5fead47134e1b831576476e6ba8d82893e20d236506429fd6a227fe96ed",
    "encodedWidth": 4032,
    "encodedHeight": 3024,
    "orientation": 6,
    "megapixels": 12.192768,
    "photographicMetadataPresent": true,
    "objectKey": "photos/fuji-28cca5fead47134e1b831576476e6ba8d82893e20d236506429fd6a227fe96ed.jpg",
    "variants": [
      {
        "file": "fuji-480.webp",
        "width": 480,
        "height": 640,
        "bytes": 21206,
        "sha256": "a0e84c267d9f56c1d47861dd11ed79dc4d7971d572b64e922e006432300bc8fe"
      },
      {
        "file": "fuji-800.webp",
        "width": 800,
        "height": 1067,
        "bytes": 52586,
        "sha256": "96a54e78f21ca6a9ea278880a352616523524aa8d38afc2d7a0679267a08c1b5"
      },
      {
        "file": "fuji-1200.webp",
        "width": 1200,
        "height": 1600,
        "bytes": 99812,
        "sha256": "09762f0b7ea906eb6e02918433d67148ab904bfb32385d83546ad2f8f390a08b"
      }
    ]
  },
  "tsutenkaku": {
    "mime": "image/jpeg",
    "width": 3024,
    "height": 4032,
    "bytes": 1963940,
    "sha256": "afd52514e34cb452d2894bcb4f1ec8d1236e935510e82975810b4be500f6dae4",
    "encodedWidth": 4032,
    "encodedHeight": 3024,
    "orientation": 6,
    "megapixels": 12.192768,
    "photographicMetadataPresent": true,
    "objectKey": "photos/tsutenkaku-afd52514e34cb452d2894bcb4f1ec8d1236e935510e82975810b4be500f6dae4.jpg",
    "variants": [
      {
        "file": "tsutenkaku-480.webp",
        "width": 480,
        "height": 640,
        "bytes": 27684,
        "sha256": "3576688ba66b753ee28b583cd720bc36ffdf7480d30e948f23995b703101f502"
      },
      {
        "file": "tsutenkaku-800.webp",
        "width": 800,
        "height": 1067,
        "bytes": 66318,
        "sha256": "0236dec8e6cc3b89d0f5fe2f744fdd023df4e2116e5d7f03c436832a1ffb3b8c"
      },
      {
        "file": "tsutenkaku-1200.webp",
        "width": 1200,
        "height": 1600,
        "bytes": 122266,
        "sha256": "2a280ef117f4c4b68e1179a4278ad0158140b30c0e0498e54bff6c11549e4c75"
      }
    ]
  },
  "shiba": {
    "mime": "image/jpeg",
    "width": 4284,
    "height": 5712,
    "bytes": 3257044,
    "sha256": "9b099a2c6c4a11389b49e5940b5b3dd6d200fb97674ecec4055c25ad4305d0f3",
    "encodedWidth": 5712,
    "encodedHeight": 4284,
    "orientation": 6,
    "megapixels": 24.470208,
    "photographicMetadataPresent": true,
    "objectKey": "photos/shiba-9b099a2c6c4a11389b49e5940b5b3dd6d200fb97674ecec4055c25ad4305d0f3.jpg",
    "variants": [
      {
        "file": "shiba-480.webp",
        "width": 480,
        "height": 640,
        "bytes": 35288,
        "sha256": "d4e2715edbcc1d84d498bae91922616f0bb4f36add3902bd2ec9bc206b864bc4"
      },
      {
        "file": "shiba-800.webp",
        "width": 800,
        "height": 1067,
        "bytes": 69428,
        "sha256": "0ec3f1de4f7333146dbdf46f878612cc761dc8ed2e25885f74962daef6727096"
      },
      {
        "file": "shiba-1200.webp",
        "width": 1200,
        "height": 1600,
        "bytes": 122618,
        "sha256": "fee57dee94b2ae2fd7bb685b9d9e0509c490715e62c950cbdc15cc908fb1eea5"
      }
    ]
  }
} as const;
